--- 
abstract: a bridge that supports AnyEvent.pm from POE
author: "& LICENSING"
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Loop-AnyEvent
no_index: 
  directory: 
    - ex
    - inc
    - t
requires: 
  POE: 0.9999
version: 0.02
